
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/cars-factory
    username: postgres
    password: 1111
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres